
module.exports = {
  NOTES_RECEIVED: 'NOTES_RECEIVED',
  NOTE_RECEIVED: 'NOTE_RECEIVED',
  NOTE_REMOVED: 'NOTE_REMOVED',

  ASC_UPDATED: 'ASC_UPDATED',
  DESC_UPDATED: 'DESC_UPDATED',
  ASC_CREATED: 'ASC_CREATED',
  DESC_CREATED: 'DESC_CREATED'
};
