# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17b8deb8c0d0b95e4a512f4e3272d0c4ace4edd78a217e98962dc50014ca18d3958f5198192dbdda7316cb85456bbe13e5cffdfed3c081bc7026a1bc8ba7c402

test:
  secret_key_base: 44bcf8cd29d3eac370a715f8591befb96e08ed3f3966497dc4ca3368b509cf3c936b4ecb093197f594023b4cefd2c2c30ac76ab89b2c93674a26ba02ca66d94d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
